services:
  frontend:
    build:
      context: ./frontend # Pfad zum Verzeichnis mit dem Dockerfile
      dockerfile: Dockerfile # Name des Dockerfiles
    container_name: casa_app_frontend
    depends_on:
      - backend
    
    networks:
      - npm_default
    
    restart: unless-stopped